// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileSearchController from "./profile_search_controller"
application.register("profile-search", ProfileSearchController)

import TagAutocompleteController from "./tag_autocomplete_controller"
application.register("tag-autocomplete", TagAutocompleteController)

import TagDescriptionController from "./tag_description_controller"
application.register("tag-description", TagDescriptionController)

import TagToggleController from "./tag_toggle_controller"
application.register("tag-toggle", TagToggleController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)
