// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarPreviewController from "./avatar_preview_controller"
application.register("avatar-preview", AvatarPreviewController)

import CharCounterController from "./char_counter_controller"
application.register("char-counter", CharCounterController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import ProfileSearchController from "./profile_search_controller"
application.register("profile-search", ProfileSearchController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TagAutocompleteController from "./tag_autocomplete_controller"
application.register("tag-autocomplete", TagAutocompleteController)

import TagDescriptionController from "./tag_description_controller"
application.register("tag-description", TagDescriptionController)

import TagToggleController from "./tag_toggle_controller"
application.register("tag-toggle", TagToggleController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
